### ISSUE TITLE
Idea: A few functions from APL

### ISSUE THREAD

**Issue by ghost** [ZippyMagician/Arn#1]
I'd like to see some one-byte functions from APL being introduced to Arn.

* Transposition of a 2D array (`⍉`)
* 1-range (`⍳`)
* Random number in range(1..input) (`?`)
* ceiling (`⌈`)
* floor (`⌊`)

**Comment by ZippyMagician** [comment]
Due to the packing only taking ascii characters, these probably won't become 1-byte functions. However, some of these could be useful as future 2-byte fixes. Furthermore, two of these exist already:
- `:v` -> floor
- `:^` -> Ceiling

~~Also, could you clarify what the 1-range function does? I'm pretty rusty with APL~~ I don't know how I didn't realize what it does from the name XD... yeah I'll probably add this in the future

**Comment by ZippyMagician** [comment]
Added in the latest update (along with `:+` and `:-`) So I'm closing this suggestion.

**Comment by A-ee** [comment]
@ZippyMagician Well, isn't `:+` and `:-` basically the same length as `*2` and `/2`?
